### ISSUE TITLE
请教下性能上immutability-helper-x（或者immutability-helper） 和 immutable-js 有区别吗？ 

### ISSUE THREAD

**Issue by YutHelloWorld** [ProtoTeam/immutability-helper-x#2]

**Comment by alanwei0** [comment]
immutabilily-helper-x比较适合同 [immutability-helper](https://github.com/kolodny/immutability-helper) 进行比较。

 - 使用 update 方法（和 immutability-helper 相同的 api），性能是一样的。

 - 使用 $xxx 方法操作：

```js
update.$set(data, ['a', 'b'], newValue);
```

性能上稍微差一点，还可以优化！但是也没有达到影响使用的程度，考虑易用和性能两方面，还是值得的。

**Comment by YutHelloWorld** [comment]
在处理react或者redux 不可变数据深层数据结构的时候，我试了helper和immutable-js,易用性上当然是helper-x 更好，immutable-js的Map结构不是很适合react的state, 但是社区吹捧immutable-js比较多，所以有immutability-helper-x和immutable-js之间优缺点比较的疑惑

**Comment by alanwei0** [comment]
性能上我们没有进行准确的统计，但是可以跟你讲一下我们当时选择immutability-helper而不是immutable.js的几点考虑：

1. immutability-helper的api比较简单，并且返回结果依旧是原生js对象，该怎么操作还是操作，学习成本低，这样对于整个团队成员来说更容易接受。
2. 接着上一点，由于是原生js对象和数组，所以在项目中依然可以方便地使用lodash这样的函数库

**Comment by YutHelloWorld** [comment]
谢谢，受教了~👏
